title: This is me
author: Ruthann Wheeler
email: rarudd1@juno.com
description: > This is the description

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
